### ISSUE TITLE
undeclared identifier '__hipsycl_warp_size' with --hipsycl-explicit-multipass

### ISSUE THREAD

**Issue by Luigi-Crisci** [AdaptiveCpp/AdaptiveCpp#685]
**Bug summary**
When a program is compiled using "--hipsycl-explicit-multipass" this error occurs. Probably introduced in 542a602fd93eac924168ea523641da3099feaec7.

```bash
HIPSYCL_TARGETS=cuda:sm_60 syclcc --hipsycl-explicit-multipass test.cpp
```
The output:
```bash
use of undeclared identifier '__hipsycl_warp_size'
      if constexpr(DivisorX % __hipsycl_warp_size == 0) {
                              ^
/root/build_hipsycl/bin/../include/hipSYCL/glue/cuda/../generic/hiplike/hiplike_kernel_launcher.hpp:295:52: error: use of undeclared identifier '__hipsycl_warp_size'
                         nested_range<static_range<__hipsycl_warp_size>>>;
                                                   ^
/root/build_hipsycl/bin/../include/hipSYCL/glue/cuda/../generic/hiplike/hiplike_kernel_launcher.hpp:297:16: error: use of undeclared identifier 'decomposition'
        return decomposition{};
               ^
/root/build_hipsycl/bin/../include/hipSYCL/glue/cuda/../generic/hiplike/hiplike_kernel_launcher.hpp:517:14: error: use of undeclared identifier 'hiplike'
  __device__ hiplike::local_reducer<ReductionDescriptor>
```

**To Reproduce**
Compile any program with "--hipsycl-explicit-multipass".  I tried on this one: https://gist.github.com/Luigi-Crisci/aa62113dc868f129cd2c1f09e1b72930

*My setup*
* HipSYCL at ee8cd86f95fe5604b6cf130d724828f7f5f0e121, compiled with Cuda backend
* Clang 11
* CXX compiler: G++ 9
* CUDA 10.1

**Comment by illuhad** [comment]
Thanks for reporting. I think this happens because in current explicit multipass, the host pass is a pure C++ pass, so it's not possible to query warp size.

It's not yet tested with clang 11 (mostly clang 13+), but we have a major rework of explicit multipass coming up in this PR: #683. This PR also changes which features are available in the host pass, so it might fix this issue. Can you give it a try?

Also, for more performance with explicit multipass kernels I would recommend #684 :-)

**Comment by Luigi-Crisci** [comment]
I tried with https://github.com/illuhad/hipSYCL/pull/683 and it works fine, thanks!

Just a little error:
there is a misplaced if at line 1050 in the syclcc
```python
    for mb in self._multipass_backends:
      reqs = mb.get_host_pass_requirements()['requires-extended-host-pass']
      if  <-- this one
```
I see that it has been fixed in the branch *feature/revisit-explicit-multipass*, but it is still present in the pull request.

**Comment by illuhad** [comment]
Can you clarify? The pull request is for exactly this branch, and in line 1050 the PR has completely different content?

**Comment by Luigi-Crisci** [comment]
Pulling https://github.com/illuhad/hipSYCL/pull/683, last commit is https://github.com/illuhad/hipSYCL/pull/683/commits/b748a9e23afb26c6d36c92980041896cacb05c31. Here, in syclcc there is the error (link: https://github.com/illuhad/hipSYCL/blob/b748a9e23afb26c6d36c92980041896cacb05c31/bin/syclcc-clang, line 1050)
I'm sorry if my comment was misleading.

**Comment by illuhad** [comment]
Ah, I think b748a9e is the first commit contained in this PR, not the last one - so basically, once we merge this PR your issue should be solved :)

**Comment by Luigi-Crisci** [comment]
Oh sorry, I checked out to the first commit instead of the last one 🤦.
Thanks for helping, and sorry for that :c
