### ISSUE TITLE
compiler error: reference to __host__ function 'XXXXX' in __host__ __device__ function

### ISSUE THREAD

**Issue by cgleggett** [AdaptiveCpp/AdaptiveCpp#501]
I have some SYCL code that compiles fine with Intel dpcpp, but with hipSYCL 0.9.0 produces the following error message when trying to compile for an AMD GPU:

```
/opt/hipSYCL/bin/syclcc -DActsCore_EXPORTS -DBOOST_ALL_NO_LIB -I/home/acts/hipSycl/src/Core/include -I/home/acts/hipSycl/bld/Core -isystem /opt/boost/1.72.0/include -isystem /opt/eigen/3.3.9/include/eigen3 --hipsycl-targets=hip:gfx900 -Wall -Wextra -Wpedantic -Wshadow -Wunused-local-typedefs -O2 -g -DNDEBUG  -fPIC -o CMakeFiles/ActsCore.dir/src/EventData/NeutralTrackParameters.cpp.o -c /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp
In file included from /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:9:
In file included from /home/acts/hipSycl/src/Core/include/Acts/EventData/NeutralTrackParameters.hpp:12:
/home/acts/hipSycl/src/Core/include/Acts/EventData/SingleBoundTrackParameters.hpp:222:46: error: reference to __host__ function 'get<Acts::eBoundQOverP>' in __host__ __device__ function
    return m_chargeInterpreter.extractCharge(get<eBoundQOverP>());

```
There is no usage of `__host__` or `__device__` anywhere in the code, not even from the include files which I verified by add `-E` to the compilation line.

this looks suspiciously like it's trying to produce some cuda code.

Any advice as to what could be causing this?

**Comment by illuhad** [comment]
Well, hipSYCL uses clang CUDA/HIP for code generation, so under the hood there really is CUDA/HIP compilation taking place. This is why you can use CUDA or HIP code directly from hipSYCL.

Do you have this code available somewhere? It looks like it fails to outline the kernel. Also please describe how you have installed hipSYCL and attach the output of the compilation command when setting the environment variable `HIPSYCL_DEBUG_LEVEL=3`, as well as separately, the output of the compilation command when setting the environment variable `HIPSYCL_DRYRUN=1`.

**Comment by cgleggett** [comment]
hipSYCL was installed from the rpms at http://repo.urz.uni-heidelberg.de/sycl/test-plugin/rpm/
 (for a CentOS7 system):
```
> rpm -qa | grep hipSYCL
hipSYCL-omp-nightly-0.9.0-20210312.x86_64
hipSYCL-rocm-nightly-0.9.0-20210312.x86_64
hipSYCL-base-0.8.1-20200320.x86_64
hipSYCL-base-rocm-nightly-0.9.0-20210312.x86_64
hipSYCL-core-nightly-0.9.0-20210312.x86_64
hipSYCL-base-nightly-0.9.0-20210312.x86_64
```


in order to reproduce, you will need to also install boost and eigen3. then:

```
> echo $CMAKE_PREFIX_PATH
/opt/eigen/3.3.9:/opt/boost/1.72.0
> export CXX=/opt/hipSYCL/bin/syclcc
> git clone git@github.com:/acts-project/acts.git src
> mkdir bld
> cd bld
> cmake -DACTS_BUILD_UNITTESTS=ON -DACTS_BUILD_PLUGIN_TGEO=off -DACTS_BUILD_PLUGIN_SYCL=on -DCMAKE_CXX_FLAGS=--hipsycl-targets=hip:gfx900 ../src
> make -C Tests/UnitTests/Plugins/Sycl
```


adding `HIPSYCL_DRYRUN=1` gives this:
```
/opt/hipSYCL/bin/syclcc -DActsCore_EXPORTS -DBOOST_ALL_NO_LIB -I/home/acts/hipSycl/src/Core/include -I/home/acts/hipSycl/bld2/Core -isystem /opt/boost/1.72.0/include -isystem /opt/eigen/3.3.9/include/eigen3 --hipsycl-targets=hip:gfx900 -Wall -Wextra -Wpedantic -Wshadow -Wunused-local-typedefs -O2 -g -DNDEBUG  -fPIC -o CMakeFiles/ActsCore.dir/src/EventData/NeutralTrackParameters.cpp.o -c /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp
/opt/hipSYCL/llvm/llvm/bin/clang++ -I/bld4/opt/hipSYCL/bin/../include/ -D__HIPSYCL__ -std=c++17 -isystem /opt/hipSYCL/llvm/llvm/lib/clang/11.0.0/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I/opt/hipSYCL/rocm/hsa-rocr-dev/include -I/opt/hipSYCL/rocm/hip/include --rocm-path=/opt/hipSYCL/rocm/rocm-device-libs -x hip -D__HIPSYCL_ENABLE_HIP_TARGET__ -fplugin=/bld4/opt/hipSYCL/bin/../lib/libhipSYCL_clang.so -D__HIPSYCL_CLANG__ --cuda-gpu-arch=gfx900 -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -I/opt/hipSYCL/boost/boost/include -DActsCore_EXPORTS -DBOOST_ALL_NO_LIB -I/home/acts/hipSycl/src/Core/include -I/home/acts/hipSycl/bld2/Core -isystem /opt/boost/1.72.0/include -isystem /opt/eigen/3.3.9/include/eigen3 -Wall -Wextra -Wpedantic -Wshadow -Wunused-local-typedefs -O2 -g -DNDEBUG -fPIC -o CMakeFiles/ActsCore.dir/src/EventData/NeutralTrackParameters.cpp.o -c /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp
```


adding `HIPSYCL_DEBUG_LEVEL=3` gives this (I truncated the error message in the original description):
```
/opt/hipSYCL/bin/syclcc -DActsCore_EXPORTS -DBOOST_ALL_NO_LIB -I/home/acts/hipSycl/src/Core/include -I/home/acts/hipSycl/bld2/Core -isystem /opt/boost/1.72.0/include -isystem /opt/eigen/3.3.9/include/eigen3 --hipsycl-targets=hip:gfx900 -Wall -Wextra -Wpedantic -Wshadow -Wunused-local-typedefs -O2 -g -DNDEBUG  -fPIC -o CMakeFiles/ActsCore.dir/src/EventData/NeutralTrackParameters.cpp.o -c /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp
In file included from /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:9:
In file included from /home/acts/hipSycl/src/Core/include/Acts/EventData/NeutralTrackParameters.hpp:12:
/home/acts/hipSycl/src/Core/include/Acts/EventData/SingleBoundTrackParameters.hpp:222:46: error: reference to __host__ function 'get<Acts::eBoundQOverP>' in __host__ __device__ function
    return m_chargeInterpreter.extractCharge(get<eBoundQOverP>());
                                             ^
/home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:16:16: note: in instantiation of member function 'Acts::SingleBoundTrackParameters<Acts::Neutral>::charge' requested here
template class SingleBoundTrackParameters<Neutral>;
               ^
/home/acts/hipSycl/src/Core/include/Acts/EventData/SingleBoundTrackParameters.hpp:163:10: note: 'get<Acts::eBoundQOverP>' declared here
  Scalar get() const {
         ^
In file included from /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:9:
In file included from /home/acts/hipSycl/src/Core/include/Acts/EventData/NeutralTrackParameters.hpp:14:
/home/acts/hipSycl/src/Core/include/Acts/EventData/SingleFreeTrackParameters.hpp:184:46: error: reference to __host__ function 'get<Acts::eFreeQOverP>' in __host__ __device__ function
    return m_chargeInterpreter.extractCharge(get<eFreeQOverP>());
                                             ^
/home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:18:16: note: in instantiation of member function 'Acts::SingleFreeTrackParameters<Acts::Neutral>::charge' requested here
template class SingleFreeTrackParameters<Neutral>;
               ^
/home/acts/hipSycl/src/Core/include/Acts/EventData/SingleFreeTrackParameters.hpp:140:10: note: 'get<Acts::eFreeQOverP>' declared here
  Scalar get() const {
         ^
In file included from /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:11:
/home/acts/hipSycl/src/Core/include/Acts/EventData/TrackParametersConcept.hpp:103:3: error: static_assert failed due to requirement 'hasMethodCharge' "Missing or invalid 'charge' method"
  static_assert(hasMethodCharge, "Missing or invalid 'charge' method");
  ^             ~~~~~~~~~~~~~~~
/home/acts/hipSycl/src/Core/include/Acts/EventData/TrackParametersConcept.hpp:168:5: note: in instantiation of template class 'Acts::Concepts::BoundTrackParametersConceptImpl<Acts::SingleBoundTrackParameters<Acts::Neutral>>' requested here
    BoundTrackParametersConceptImpl<parameters_t>::value;
    ^
/home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:22:15: note: in instantiation of variable template specialization 'Acts::Concepts::BoundTrackParametersConcept<Acts::SingleBoundTrackParameters<Acts::Neutral>>' requested here
    Concepts::BoundTrackParametersConcept<NeutralBoundTrackParameters>);
              ^
/home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:22:5: error: static_assert expression is not an integral constant expression
    Concepts::BoundTrackParametersConcept<NeutralBoundTrackParameters>);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:11:
/home/acts/hipSycl/src/Core/include/Acts/EventData/TrackParametersConcept.hpp:103:3: error: static_assert failed due to requirement 'hasMethodCharge' "Missing or invalid 'charge' method"
  static_assert(hasMethodCharge, "Missing or invalid 'charge' method");
  ^             ~~~~~~~~~~~~~~~
/home/acts/hipSycl/src/Core/include/Acts/EventData/TrackParametersConcept.hpp:168:5: note: in instantiation of template class 'Acts::Concepts::BoundTrackParametersConceptImpl<Acts::SingleCurvilinearTrackParameters<Acts::Neutral>>' requested here
    BoundTrackParametersConceptImpl<parameters_t>::value;
    ^
/home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:24:15: note: in instantiation of variable template specialization 'Acts::Concepts::BoundTrackParametersConcept<Acts::SingleCurvilinearTrackParameters<Acts::Neutral>>' requested here
    Concepts::BoundTrackParametersConcept<NeutralCurvilinearTrackParameters>);
              ^
/home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:24:5: error: static_assert expression is not an integral constant expression
    Concepts::BoundTrackParametersConcept<NeutralCurvilinearTrackParameters>);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:11:
/home/acts/hipSycl/src/Core/include/Acts/EventData/TrackParametersConcept.hpp:157:3: error: static_assert failed due to requirement 'hasMethodCharge' "Missing or invalid 'charge' method"
  static_assert(hasMethodCharge, "Missing or invalid 'charge' method");
  ^             ~~~~~~~~~~~~~~~
/home/acts/hipSycl/src/Core/include/Acts/EventData/TrackParametersConcept.hpp:172:5: note: in instantiation of template class 'Acts::Concepts::FreeTrackParametersConceptImpl<Acts::SingleFreeTrackParameters<Acts::Neutral>>' requested here
    FreeTrackParametersConceptImpl<parameters_t>::value;
    ^
/home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:25:25: note: in instantiation of variable template specialization 'Acts::Concepts::FreeTrackParametersConcept<Acts::SingleFreeTrackParameters<Acts::Neutral>>' requested here
static_assert(Concepts::FreeTrackParametersConcept<NeutralFreeTrackParameters>);
                        ^
/home/acts/hipSycl/src/Core/src/EventData/NeutralTrackParameters.cpp:25:15: error: static_assert expression is not an integral constant expression
static_assert(Concepts::FreeTrackParametersConcept<NeutralFreeTrackParameters>);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[hipSYCL Info]  ****** Entering compilation mode for __device__ ****** 
8 errors generated when compiling for gfx900.
```

**Comment by vrpascuzzi** [comment]
@cgleggett,

`--cuda-gpu-arch=gfx900` doesn't look right to me...however must still compile for HIP as I see the same compiling a simple test:
```
$ HIPSYCL_DRYRUN=1 /opt/hipSYCL/bin/syclcc -O2 \
  -DSYCL_TARGET_AMD\
  --hipsycl-targets=hip:gfx900,gfx906,gfx908 \
  -o hip_test hip_test.cc
/opt/hipSYCL/llvm/llvm/bin/clang++ -I/bld4/opt/hipSYCL/bin/../include/ -D__HIPSYCL__ -std=c++17 -isystem \
/opt/hipSYCL/llvm/llvm/lib/clang/11.0.0/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ \
-I/opt/hipSYCL/rocm/hsa-rocr-dev/include -I/opt/hipSYCL/rocm/hip/include \
--rocm-path=/opt/hipSYCL/rocm/rocm-device-libs -x hip -D__HIPSYCL_ENABLE_HIP_TARGET__ \
-fplugin=/bld4/opt/hipSYCL/bin/../lib/libhipSYCL_clang.so -D__HIPSYCL_CLANG__ \
--cuda-gpu-arch=gfx900 --cuda-gpu-arch=gfx906 --cuda-gpu-arch=gfx908 \
-D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -I/opt/hipSYCL/boost/boost/include \
-DSYCL_TARGET_AMD -o hip_test hip_test.cc -L/bld4/opt/hipSYCL/bin/../lib/ \
-lhipSYCL-rt -Wl,-rpath=/bld4/opt/hipSYCL/bin/../lib/ -Wl,-rpath=/opt/hipSYCL/rocm/lib \
-Wl,-rpath=/opt/hipSYCL/rocm/hip/lib -Wl,-rpath=/opt/hipSYCL/llvm/llvm/lib -L/opt/hipSYCL/rocm/lib \
-L/opt/hipSYCL/rocm/hip/lib -lamdhip64 -L/opt/hipSYCL/boost/boost/lib -lboost_context -lboost_fiber \
-lomp  -Wl,-rpath=/opt/hipSYCL/boost/boost/lib
```

**Comment by illuhad** [comment]
@vrpascuzzi `--cuda-gpu-arch` is in fact correct as the the clang CUDA and HIP toolchains share a lot of infrastructure, including compiler arguments. Only recently was `--offload-arch` added as a more neutral sounding alternative, but `--cuda-gpu-arch` still works and is the traditional way of compiling for HIP since the original introduction of HIP support in clang 8 :)

**Comment by illuhad** [comment]
@cgleggett 

thanks, I could reproduce the issue. 

First, I would suggest to use proper cmake integration with hipSYCL using `find_package(hipSYCL)` and `add_sycl_to_target()`. cmake tends to not like having unknown compilers set as `CMAKE_CXX_COMPILER`, especially if they may end up invoking different toolchains like `syclcc` does.

Your issue is triggered during initial parsing of the code by clang, before hipSYCL even sees the AST and starts working on it. It's not a hipSYCL issue, but a case of incorrect `constexpr` in the code which however triggers a somewhat misleading error message from clang.

In CUDA/HIP compilation modes, `constexpr` functions are implicitly `__host__ __device__`. This is why the function was treated as `__host__ __device__` by clang. However, it calls non-constexpr code in the form of `get<>()`, which is therefore just a regular `__host__` function. As a consequence, clang complains about a call to a `__host__` function from `__host__ __device__` code. A correct error message describing the root issue would have been that `charge()` cannot be `constexpr`.

Solution: Remove `constexpr` and it works (note: there are actually two files where this happens, both need to be fixed).

I'm not sure how the offending class fits into your framework, but for the sake of completeness would like to point out that you will face issues if you actually try using it in SYCL kernels because it does not obey SYCL kernel restrictions. But maybe the class is not intended to be used inside a kernel, in which case it's fine.

**Comment by cgleggett** [comment]
Thanks Aksel!
