### ISSUE TITLE
Not able to compile with Cuda 9.2

### ISSUE THREAD

**Issue by abboomer** [AdaptiveCpp/AdaptiveCpp#354]
I'm now trying to build hipSYCL with cuda 9.2 and clang-llmv 8.

I'm getting the following compiler errors:

```
/hipSYCL/src/runtime/cuda/cuda_allocator.cpp: In member function ‘virtual hipsycl::rt::result hipsycl::rt::cuda_allocator::query_pointer(const void*, hipsycl::rt::pointer_info&) const’:
/hipSYCL/src/runtime/cuda/cuda_allocator.cpp:141:15: error: ‘struct cudaPointerAttributes’ has no member named ‘type’
   if (attribs.type == cudaMemoryTypeUnregistered) {
               ^~~~
/hipSYCL/src/runtime/cuda/cuda_allocator.cpp:141:23: error: ‘cudaMemoryTypeUnregistered’ was not declared in this scope
   if (attribs.type == cudaMemoryTypeUnregistered) {

```
As of cuda 10.0, the cudaPointerAttributes::type is deprecated.
[Here's the 9.2 documentation](https://docs.nvidia.com/cuda/archive/9.2/cuda-runtime-api/structcudaPointerAttributes.html#structcudaPointerAttributes).
[Here's the 10.0 documentation](https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/structcudaPointerAttributes.html#structcudaPointerAttributes).

**So, does this mean that Cuda 9.2 is not supported?**

And if its true that Cuda >= 10 is supported, it should be noted that clang-llvm only supports Cuda 7.0 - 10.1 (see [here](http://llvm.org/docs/CompileCudaWithLLVM.html)).
**All meaning that the only version of Cuda that is supported is 10.1?** 
Yesterday, I was able to build hipSYCL with Cuda 11.1, but couldn't get clang++ to work with Cuda 11.1. So, now it seems that I'm stuck with Cuda 10.1.  Any help appreciated, I'm probably missing something, because the hipSYCL docs say that Cuda 9.2 is indeed supported.

Thank you!

**Comment by illuhad** [comment]
clang only officially supports up to CUDA 10.1, but clang 10 detects CUDA versions up to 11.0 (and treats them the same as 10.1, which is usually fine). This means that CUDA up to 11.0 is expected to work. Even if 9.2 doesn't work, 10.0, 10.1, 10.2 and 11.0 will. For clang 8 the most recent detected CUDA version might be older.

I'm not aware of `cudaPointerAttributes::type` being deprecated, and the 10.0 documentation you have linked does not list it as such. Neither does the documentation for 11.0.

We see very little use of 9.2 and don't test regularly with it anymore. The code that is causing this issue is fairly recent, and apparently it broke 9.2 support. We need the `type` to implement SYCL 2020 USM. Maybe a workaround for 9.2 is possible, but given the age of CUDA 9.2 it might be more appropriate to drop support for it.

EDIT: Your clang is quite old. I recommend switching to a newer one if you wish to use newer CUDA versions.

**Comment by abboomer** [comment]
Thanks for the quick reply! OK, that's good to know.
For the record, I was mistaken--I am using clang-llvm 9, not that that changes what you're saying.

I'll upgrade to Cuda 10.1 as its tough to find pre-built clang-llvm 10 for Centos 7...
I'm dealing with some backwards compatibility issues :)
